/*
 * Code-owned canonical scaffold source bytes. Keep these product-neutral.
 * Exact identities and semantic closure are pinned by the asset and catalog tests.
 */
function textV2(...parts: readonly string[]): string {
  return parts.join("");
}

export const NODE_CLI_PACKAGE_JSON_TEXT_V2 = textV2(
  "{\"devDependencies\":{\"@types/node\":\"22.19.11\",\"typescript\":\"5.9.3\"},\"engines\":{\"node\":\">=22.13.0 ",
  "<23\",\"npm\":\"10.9.8\"},\"name\":\"@setfarm/generated-node-cli-v2\",\"packageManager\":\"npm@10.9.8\",\"priv",
  "ate\":true,\"scripts\":{\"build\":\"tsc -p tsconfig.json\",\"test\":\"node --test\"},\"type\":\"module\",\"versi",
  "on\":\"0.0.0\"}\n",
);
export const NODE_CLI_PACKAGE_LOCK_JSON_TEXT_V2 = textV2(
  "{\"lockfileVersion\":3,\"name\":\"@setfarm/generated-node-cli-v2\",\"packages\":{\"\":{\"devDependencies\":{",
  "\"@types/node\":\"22.19.11\",\"typescript\":\"5.9.3\"},\"engines\":{\"node\":\">=22.13.0 <23\",\"npm\":\"10.9.8\"}",
  ",\"name\":\"@setfarm/generated-node-cli-v2\",\"version\":\"0.0.0\"},\"node_modules/@types/node\":{\"depende",
  "ncies\":{\"undici-types\":\"~6.21.0\"},\"dev\":true,\"integrity\":\"sha512-BH7YwL6rA93ReqeQS1c4bsPpcfOmJas",
  "G+Fkr6Y59q83f9M1WcBRHR2vM+P9eOisYRcN3ujQoiZY8uk5W+1WL8w==\",\"license\":\"MIT\",\"resolved\":\"https://r",
  "egistry.npmjs.org/@types/node/-/node-22.19.11.tgz\",\"version\":\"22.19.11\"},\"node_modules/typescrip",
  "t\":{\"bin\":{\"tsc\":\"bin/tsc\",\"tsserver\":\"bin/tsserver\"},\"dev\":true,\"engines\":{\"node\":\">=14.17\"},\"i",
  "ntegrity\":\"sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wt",
  "m6M5TgSw==\",\"license\":\"Apache-2.0\",\"resolved\":\"https://registry.npmjs.org/typescript/-/typescrip",
  "t-5.9.3.tgz\",\"version\":\"5.9.3\"},\"node_modules/undici-types\":{\"dev\":true,\"integrity\":\"sha512-iwDZ",
  "qg0QAGrg9Rav5H4n0M64c3mkR59cJ6wQp+7C4nI0gsmExaedaYLNO44eT4AtBBwjbTiGPMlt2Md0T9H9JQ==\",\"license\":",
  "\"MIT\",\"resolved\":\"https://registry.npmjs.org/undici-types/-/undici-types-6.21.0.tgz\",\"version\":\"",
  "6.21.0\"}},\"requires\":true,\"version\":\"0.0.0\"}\n",
);
export const NODE_CLI_TSCONFIG_JSON_TEXT_V2 = textV2(
  "{\"compilerOptions\":{\"esModuleInterop\":true,\"forceConsistentCasingInFileNames\":true,\"module\":\"Nod",
  "eNext\",\"moduleResolution\":\"NodeNext\",\"noEmitOnError\":true,\"outDir\":\"dist\",\"resolveJsonModule\":tr",
  "ue,\"rootDir\":\"src\",\"strict\":true,\"target\":\"ES2022\",\"verbatimModuleSyntax\":true},\"exclude\":[\"dist",
  "\",\"node_modules\"],\"include\":[\"src/**/*.ts\"]}\n",
);

export const NODE_EXPRESS_API_PACKAGE_JSON_TEXT_V2 = textV2(
  "{\"dependencies\":{\"express\":\"5.2.1\"},\"devDependencies\":{\"@types/express\":\"5.0.6\",\"@types/node\":\"2",
  "2.19.11\",\"typescript\":\"5.9.3\"},\"engines\":{\"node\":\">=22.13.0 <23\",\"npm\":\"10.9.8\"},\"name\":\"@setfar",
  "m/generated-node-express-api-v2\",\"packageManager\":\"npm@10.9.8\",\"private\":true,\"scripts\":{\"build\"",
  ":\"tsc -p tsconfig.json\",\"test\":\"node --test\"},\"type\":\"module\",\"version\":\"0.0.0\"}\n",
);
export const NODE_EXPRESS_API_PACKAGE_LOCK_JSON_TEXT_V2 = textV2(
  "{\"lockfileVersion\":3,\"name\":\"@setfarm/generated-node-express-api-v2\",\"packages\":{\"\":{\"dependenci",
  "es\":{\"express\":\"5.2.1\"},\"devDependencies\":{\"@types/express\":\"5.0.6\",\"@types/node\":\"22.19.11\",\"ty",
  "pescript\":\"5.9.3\"},\"engines\":{\"node\":\">=22.13.0 <23\",\"npm\":\"10.9.8\"},\"name\":\"@setfarm/generated-",
  "node-express-api-v2\",\"version\":\"0.0.0\"},\"node_modules/@types/body-parser\":{\"dependencies\":{\"@typ",
  "es/connect\":\"*\",\"@types/node\":\"*\"},\"dev\":true,\"integrity\":\"sha512-HLFeCYgz89uk22N5Qg3dvGvsv46B8G",
  "LvKKo1zKG4NybA8U2DiEO3w9lqGg29t/tfLRJpJ6iQxnVw4OnB7MoM9g==\",\"license\":\"MIT\",\"resolved\":\"https://",
  "registry.npmjs.org/@types/body-parser/-/body-parser-1.19.6.tgz\",\"version\":\"1.19.6\"},\"node_module",
  "s/@types/connect\":{\"dependencies\":{\"@types/node\":\"*\"},\"dev\":true,\"integrity\":\"sha512-K6uROf1LD88",
  "uDQqJCktA4yzL1YYAK6NgfsI0v/mTgyPKWsX1CnJ0XPSDhViejru1GcRkLWb8RlzFYJRqGUbaug==\",\"license\":\"MIT\",\"",
  "resolved\":\"https://registry.npmjs.org/@types/connect/-/connect-3.4.38.tgz\",\"version\":\"3.4.38\"},\"",
  "node_modules/@types/express\":{\"dependencies\":{\"@types/body-parser\":\"*\",\"@types/express-serve-sta",
  "tic-core\":\"^5.0.0\",\"@types/serve-static\":\"^2\"},\"dev\":true,\"integrity\":\"sha512-sKYVuV7Sv9fbPIt/44",
  "2koC7+IIwK5olP1KWeD88e/idgoJqDm3JV/YUiPwkoKK92ylff2MGxSz1CSjsXelx0YA==\",\"license\":\"MIT\",\"resolve",
  "d\":\"https://registry.npmjs.org/@types/express/-/express-5.0.6.tgz\",\"version\":\"5.0.6\"},\"node_modu",
  "les/@types/express-serve-static-core\":{\"dependencies\":{\"@types/node\":\"*\",\"@types/qs\":\"*\",\"@types",
  "/range-parser\":\"*\",\"@types/send\":\"*\"},\"dev\":true,\"integrity\":\"sha512-d3KvEXBSo/lOAMc2u6fkyDHBvet",
  "BHeqD7wm/AcXfLpSOQwlmG9D/aQ0SFswVjv05p7ullQS7Mjohj6/VdbZuTg==\",\"license\":\"MIT\",\"resolved\":\"https",
  "://registry.npmjs.org/@types/express-serve-static-core/-/express-serve-static-core-5.1.2.tgz\",\"v",
  "ersion\":\"5.1.2\"},\"node_modules/@types/http-errors\":{\"dev\":true,\"integrity\":\"sha512-r8Tayk8HJnX0F",
  "ztbZN7oVqGccWgw98T/0neJphO91KkmOzug1KkofZURD4UaD5uH8AqcFLfdPErnBod0u71/qg==\",\"license\":\"MIT\",\"re",
  "solved\":\"https://registry.npmjs.org/@types/http-errors/-/http-errors-2.0.5.tgz\",\"version\":\"2.0.5",
  "\"},\"node_modules/@types/node\":{\"dependencies\":{\"undici-types\":\"~6.21.0\"},\"dev\":true,\"integrity\":",
  "\"sha512-BH7YwL6rA93ReqeQS1c4bsPpcfOmJasG+Fkr6Y59q83f9M1WcBRHR2vM+P9eOisYRcN3ujQoiZY8uk5W+1WL8w==",
  "\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/@types/node/-/node-22.19.11.tgz\",\"versi",
  "on\":\"22.19.11\"},\"node_modules/@types/qs\":{\"dev\":true,\"integrity\":\"sha512-GZHUBZR9hckSUhrxmp1nG6N",
  "wdpM9fCunJwyThLW1X3AyHgd9IlHb6VANpQQqDr2o/qQp6McZ3y/IA2rVzKzSbw==\",\"license\":\"MIT\",\"resolved\":\"h",
  "ttps://registry.npmjs.org/@types/qs/-/qs-6.15.1.tgz\",\"version\":\"6.15.1\"},\"node_modules/@types/ra",
  "nge-parser\":{\"dev\":true,\"integrity\":\"sha512-hKormJbkJqzQGhziax5PItDUTMAM9uE2XXQmM37dyd4hVM+5aVl7",
  "oVxMVUiVQn2oCQFN/LKCZdvSM0pFRqbSmQ==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/@ty",
  "pes/range-parser/-/range-parser-1.2.7.tgz\",\"version\":\"1.2.7\"},\"node_modules/@types/send\":{\"depen",
  "dencies\":{\"@types/node\":\"*\"},\"dev\":true,\"integrity\":\"sha512-arsCikDvlU99zl1g69TcAB3mzZPpxgw0UQna",
  "HeC1Nwb015xp8bknZv5rIfri9xTOcMuaVgvabfIRA7PSZVuZIQ==\",\"license\":\"MIT\",\"resolved\":\"https://regist",
  "ry.npmjs.org/@types/send/-/send-1.2.1.tgz\",\"version\":\"1.2.1\"},\"node_modules/@types/serve-static\"",
  ":{\"dependencies\":{\"@types/http-errors\":\"*\",\"@types/node\":\"*\"},\"dev\":true,\"integrity\":\"sha512-8ma",
  "m4H1NHLtu7nmtalF7eyBH14QyOASmcxHhSfEoRyr0nP/YdoesEtU+uSRvMe96TW/HPTtkoKqQLl53N7UXMQ==\",\"license\"",
  ":\"MIT\",\"resolved\":\"https://registry.npmjs.org/@types/serve-static/-/serve-static-2.2.0.tgz\",\"ver",
  "sion\":\"2.2.0\"},\"node_modules/accepts\":{\"dependencies\":{\"mime-types\":\"^3.0.0\",\"negotiator\":\"^1.0.",
  "0\"},\"engines\":{\"node\":\">= 0.6\"},\"integrity\":\"sha512-5cvg6CtKwfgdmVqY1WIiXKc3Q1bkRqGLi+2W/6ao+6Y7",
  "gu/RCwRuAhGEzh5B4KlszSuTLgZYuqFqo5bImjNKng==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs",
  ".org/accepts/-/accepts-2.0.0.tgz\",\"version\":\"2.0.0\"},\"node_modules/body-parser\":{\"dependencies\":",
  "{\"bytes\":\"^3.1.2\",\"content-type\":\"^2.0.0\",\"debug\":\"^4.4.3\",\"http-errors\":\"^2.0.1\",\"iconv-lite\":\"",
  "^0.7.2\",\"on-finished\":\"^2.4.1\",\"qs\":\"^6.15.2\",\"raw-body\":\"^3.0.2\",\"type-is\":\"^2.1.0\"},\"engines\":",
  "{\"node\":\">=18\"},\"funding\":{\"type\":\"opencollective\",\"url\":\"https://opencollective.com/express\"},\"",
  "integrity\":\"sha512-2cGmJupaNgg+QUwVLAucDuWuoMZ6EX9iHDRswZ5lsNYEmwPaRknMPCLZz07yTzVq/83p4o/wzbDZb",
  "BrTvGGTIw==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/body-parser/-/body-parser-2.",
  "3.0.tgz\",\"version\":\"2.3.0\"},\"node_modules/body-parser/node_modules/content-type\":{\"engines\":{\"no",
  "de\":\">=18\"},\"funding\":{\"type\":\"opencollective\",\"url\":\"https://opencollective.com/express\"},\"inte",
  "grity\":\"sha512-j/O/d7GcZCyNl7/hwZAb606rzqkyvaDctLmckbxLzHvFBzTJHuGEdodATcP3yIRoDrLHkIATJuvzbFlp/",
  "ki2cQ==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/content-type/-/content-type-2.0.",
  "0.tgz\",\"version\":\"2.0.0\"},\"node_modules/bytes\":{\"engines\":{\"node\":\">= 0.8\"},\"integrity\":\"sha512-",
  "/Nf7TyzTx6S3yRJObOAV7956r8cr2+Oj8AC5dt8wSP3BQAoeX58NoHyCU8P8zGkNXStjTSi6fzO6F0pBdcYbEg==\",\"licen",
  "se\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/bytes/-/bytes-3.1.2.tgz\",\"version\":\"3.1.2\"},\"no",
  "de_modules/call-bind-apply-helpers\":{\"dependencies\":{\"es-errors\":\"^1.3.0\",\"function-bind\":\"^1.1.",
  "2\"},\"engines\":{\"node\":\">= 0.4\"},\"integrity\":\"sha512-Sp1ablJ0ivDkSzjcaJdxEunN5/XvksFJ2sMBFfq6x0ry",
  "hQV/2b/KwFe21cMpmHtPOSij8K99/wSfoEuTObmuMQ==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs",
  ".org/call-bind-apply-helpers/-/call-bind-apply-helpers-1.0.2.tgz\",\"version\":\"1.0.2\"},\"node_modul",
  "es/call-bound\":{\"dependencies\":{\"call-bind-apply-helpers\":\"^1.0.2\",\"get-intrinsic\":\"^1.3.0\"},\"en",
  "gines\":{\"node\":\">= 0.4\"},\"funding\":{\"url\":\"https://github.com/sponsors/ljharb\"},\"integrity\":\"sha",
  "512-+ys997U96po4Kx/ABpBCqhA9EuxJaQWDQg7295H4hBphv3IZg0boBKuwYpt4YXp6MZ5AmZQnU/tyMTlRpaSejg==\",\"l",
  "icense\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/call-bound/-/call-bound-1.0.4.tgz\",\"version",
  "\":\"1.0.4\"},\"node_modules/content-disposition\":{\"engines\":{\"node\":\">=18\"},\"funding\":{\"type\":\"open",
  "collective\",\"url\":\"https://opencollective.com/express\"},\"integrity\":\"sha512-5jRCH9Z/+DRP7rkvY83B",
  "+yGIGX96OYdJmzngqnw2SBSxqCFPd0w2km3s5iawpGX8krnwSGmF0FW5Nhr0Hfai3g==\",\"license\":\"MIT\",\"resolved\"",
  ":\"https://registry.npmjs.org/content-disposition/-/content-disposition-1.1.0.tgz\",\"version\":\"1.1",
  ".0\"},\"node_modules/content-type\":{\"engines\":{\"node\":\">= 0.6\"},\"integrity\":\"sha512-nTjqfcBFEipKdX",
  "Cv4YDQWCfmcLZKm81ldF0pAopTvyrFGVbcR6P/VAAd5G7N+0tTr8QqiU0tFadD6FK4NtJwOA==\",\"license\":\"MIT\",\"res",
  "olved\":\"https://registry.npmjs.org/content-type/-/content-type-1.0.5.tgz\",\"version\":\"1.0.5\"},\"no",
  "de_modules/cookie\":{\"engines\":{\"node\":\">= 0.6\"},\"integrity\":\"sha512-yki5XnKuf750l50uGTllt6kKILY4",
  "nQ1eNIQatoXEByZ5dWgnKqbnqmTrBE5B4N7lrMJKQ2ytWMiTO2o0v6Ew/w==\",\"license\":\"MIT\",\"resolved\":\"https:",
  "//registry.npmjs.org/cookie/-/cookie-0.7.2.tgz\",\"version\":\"0.7.2\"},\"node_modules/cookie-signatur",
  "e\":{\"engines\":{\"node\":\">=6.6.0\"},\"integrity\":\"sha512-D76uU73ulSXrD1UXF4KE2TMxVVwhsnCgfAyTg9k8P6K",
  "GZjlXKrOLe4dJQKI3Bxi5wjesZoFXJWElNWBjPZMbhg==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmj",
  "s.org/cookie-signature/-/cookie-signature-1.2.2.tgz\",\"version\":\"1.2.2\"},\"node_modules/debug\":{\"d",
  "ependencies\":{\"ms\":\"^2.1.3\"},\"engines\":{\"node\":\">=6.0\"},\"integrity\":\"sha512-RGwwWnwQvkVfavKVt22F",
  "GLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==\",\"license\":\"MIT\",\"peerDepen",
  "denciesMeta\":{\"supports-color\":{\"optional\":true}},\"resolved\":\"https://registry.npmjs.org/debug/-",
  "/debug-4.4.3.tgz\",\"version\":\"4.4.3\"},\"node_modules/depd\":{\"engines\":{\"node\":\">= 0.8\"},\"integrity",
  "\":\"sha512-g7nH6P6dyDioJogAAGprGpCtVImJhpPk/roCzdb3fIh61/s/nPsfR6onyMwkCAR/OlC3yBC0lESvUoQEAssIrw",
  "==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/depd/-/depd-2.0.0.tgz\",\"version\":\"2.0",
  ".0\"},\"node_modules/dunder-proto\":{\"dependencies\":{\"call-bind-apply-helpers\":\"^1.0.1\",\"es-errors\"",
  ":\"^1.3.0\",\"gopd\":\"^1.2.0\"},\"engines\":{\"node\":\">= 0.4\"},\"integrity\":\"sha512-KIN/nDJBQRcXw0MLVhZE9",
  "iQHmG68qAVIBg9CqmUYjmQIhgij9U5MFvrqkUL5FbtyyzZuOeOt0zdeRe4UY7ct+A==\",\"license\":\"MIT\",\"resolved\":",
  "\"https://registry.npmjs.org/dunder-proto/-/dunder-proto-1.0.1.tgz\",\"version\":\"1.0.1\"},\"node_modu",
  "les/ee-first\":{\"integrity\":\"sha512-WMwm9LhRUo+WUaRN+vRuETqG89IgZphVSNkdFgeb6sS/E4OrDIN7t48CAewSH",
  "Xc6C8lefD8KKfr5vY61brQlow==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/ee-first/-/e",
  "e-first-1.1.1.tgz\",\"version\":\"1.1.1\"},\"node_modules/encodeurl\":{\"engines\":{\"node\":\">= 0.8\"},\"int",
  "egrity\":\"sha512-Q0n9HRi4m6JuGIV1eFlmvJB7ZEVxu93IrMyiMsGC0lrMJMWzRgx6WGquyfQgZVb31vhGgXnfmPNNXmxn",
  "OkRBrg==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/encodeurl/-/encodeurl-2.0.0.tgz",
  "\",\"version\":\"2.0.0\"},\"node_modules/es-define-property\":{\"engines\":{\"node\":\">= 0.4\"},\"integrity\":",
  "\"sha512-e3nRfgfUZ4rNGL232gUgX06QNyyez04KdjFrF+LTRoOXmrOgFKDg4BCdsjW8EnT69eqdYGmRpJwiPVYNrCaW3g==",
  "\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/es-define-property/-/es-define-property",
  "-1.0.1.tgz\",\"version\":\"1.0.1\"},\"node_modules/es-errors\":{\"engines\":{\"node\":\">= 0.4\"},\"integrity\"",
  ":\"sha512-Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw=",
  "=\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz\",\"vers",
  "ion\":\"1.3.0\"},\"node_modules/es-object-atoms\":{\"dependencies\":{\"es-errors\":\"^1.3.0\"},\"engines\":{\"",
  "node\":\">= 0.4\"},\"integrity\":\"sha512-HWcBoN6NileqtSydK2FqHbS/LoDd2pqrnQHLyJzBj4kOp/ky2MWMN694xOfk",
  "K8/SnUsW2DH7EfyVlydKCsm1Zw==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/es-object-a",
  "toms/-/es-object-atoms-1.1.2.tgz\",\"version\":\"1.1.2\"},\"node_modules/escape-html\":{\"integrity\":\"sh",
  "a512-NiSupZ4OeuGwr68lGIeym/ksIZMJodUGOSCZ/FSnTxcrekbvqrgdUxlJOMpijaKZVjAJrWrGs/6Jy8OMuyj9ow==\",\"",
  "license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz\",\"vers",
  "ion\":\"1.0.3\"},\"node_modules/etag\":{\"engines\":{\"node\":\">= 0.6\"},\"integrity\":\"sha512-aIL5Fx7mawVa3",
  "00al2BnEE4iNvo1qETxLrPI/o05L7z6go7fCw1J6EQmbK4FmJ2AS7kgVF/KEZWufBfdClMcPg==\",\"license\":\"MIT\",\"re",
  "solved\":\"https://registry.npmjs.org/etag/-/etag-1.8.1.tgz\",\"version\":\"1.8.1\"},\"node_modules/expr",
  "ess\":{\"dependencies\":{\"accepts\":\"^2.0.0\",\"body-parser\":\"^2.2.1\",\"content-disposition\":\"^1.0.0\",\"",
  "content-type\":\"^1.0.5\",\"cookie\":\"^0.7.1\",\"cookie-signature\":\"^1.2.1\",\"debug\":\"^4.4.0\",\"depd\":\"^2",
  ".0.0\",\"encodeurl\":\"^2.0.0\",\"escape-html\":\"^1.0.3\",\"etag\":\"^1.8.1\",\"finalhandler\":\"^2.1.0\",\"fresh",
  "\":\"^2.0.0\",\"http-errors\":\"^2.0.0\",\"merge-descriptors\":\"^2.0.0\",\"mime-types\":\"^3.0.0\",\"on-finishe",
  "d\":\"^2.4.1\",\"once\":\"^1.4.0\",\"parseurl\":\"^1.3.3\",\"proxy-addr\":\"^2.0.7\",\"qs\":\"^6.14.0\",\"range-pars",
  "er\":\"^1.2.1\",\"router\":\"^2.2.0\",\"send\":\"^1.1.0\",\"serve-static\":\"^2.2.0\",\"statuses\":\"^2.0.1\",\"type",
  "-is\":\"^2.0.1\",\"vary\":\"^1.1.2\"},\"engines\":{\"node\":\">= 18\"},\"funding\":{\"type\":\"opencollective\",\"ur",
  "l\":\"https://opencollective.com/express\"},\"integrity\":\"sha512-hIS4idWWai69NezIdRt2xFVofaF4j+6INOp",
  "JlVOLDO8zXGpUVEVzIYk12UUi2JzjEzWL3IOAxcTubgz9Po0yXw==\",\"license\":\"MIT\",\"resolved\":\"https://regis",
  "try.npmjs.org/express/-/express-5.2.1.tgz\",\"version\":\"5.2.1\"},\"node_modules/finalhandler\":{\"depe",
  "ndencies\":{\"debug\":\"^4.4.0\",\"encodeurl\":\"^2.0.0\",\"escape-html\":\"^1.0.3\",\"on-finished\":\"^2.4.1\",\"",
  "parseurl\":\"^1.3.3\",\"statuses\":\"^2.0.1\"},\"engines\":{\"node\":\">= 18.0.0\"},\"funding\":{\"type\":\"openco",
  "llective\",\"url\":\"https://opencollective.com/express\"},\"integrity\":\"sha512-S8KoZgRZN+a5rNwqTxlZZe",
  "PjT/4cnm0ROV70LedRHZ0p8u9fRID0hJUZQpkKLzro8LfmC8sx23bY6tVNxv8pQA==\",\"license\":\"MIT\",\"resolved\":\"",
  "https://registry.npmjs.org/finalhandler/-/finalhandler-2.1.1.tgz\",\"version\":\"2.1.1\"},\"node_modul",
  "es/forwarded\":{\"engines\":{\"node\":\">= 0.6\"},\"integrity\":\"sha512-buRG0fpBtRHSTCOASe6hD258tEubFoRLb",
  "4ZNA6NxMVHNw2gOcwHo9wyablzMzOA5z9xA9L1KNjk/Nt6MT9aYow==\",\"license\":\"MIT\",\"resolved\":\"https://reg",
  "istry.npmjs.org/forwarded/-/forwarded-0.2.0.tgz\",\"version\":\"0.2.0\"},\"node_modules/fresh\":{\"engin",
  "es\":{\"node\":\">= 0.8\"},\"integrity\":\"sha512-Rx/WycZ60HOaqLKAi6cHRKKI7zxWbJ31MhntmtwMoaTeF7XFH9hhBp",
  "8vITaMidfljRQ6eYWCKkaTK+ykVJHP2A==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/fresh",
  "/-/fresh-2.0.0.tgz\",\"version\":\"2.0.0\"},\"node_modules/function-bind\":{\"funding\":{\"url\":\"https://g",
  "ithub.com/sponsors/ljharb\"},\"integrity\":\"sha512-7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp",
  "6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org",
  "/function-bind/-/function-bind-1.1.2.tgz\",\"version\":\"1.1.2\"},\"node_modules/get-intrinsic\":{\"depe",
  "ndencies\":{\"call-bind-apply-helpers\":\"^1.0.2\",\"es-define-property\":\"^1.0.1\",\"es-errors\":\"^1.3.0\"",
  ",\"es-object-atoms\":\"^1.1.1\",\"function-bind\":\"^1.1.2\",\"get-proto\":\"^1.0.1\",\"gopd\":\"^1.2.0\",\"has-s",
  "ymbols\":\"^1.1.0\",\"hasown\":\"^2.0.2\",\"math-intrinsics\":\"^1.1.0\"},\"engines\":{\"node\":\">= 0.4\"},\"fund",
  "ing\":{\"url\":\"https://github.com/sponsors/ljharb\"},\"integrity\":\"sha512-9fSjSaos/fRIVIp+xSJlE6lfwh",
  "ES7LNtKaCBIamHsjr2na1BiABJPo0mOjjz8GJDURarmCPGqaiVg5mfjb98CQ==\",\"license\":\"MIT\",\"resolved\":\"http",
  "s://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.3.0.tgz\",\"version\":\"1.3.0\"},\"node_modules",
  "/get-proto\":{\"dependencies\":{\"dunder-proto\":\"^1.0.1\",\"es-object-atoms\":\"^1.0.0\"},\"engines\":{\"nod",
  "e\":\">= 0.4\"},\"integrity\":\"sha512-sTSfBjoXBp89JvIKIefqw7U2CCebsc74kiY6awiGogKtoSGbgjYE/G/+l9sF3MW",
  "FPNc9IcoOC4ODfKHfxFmp0g==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/get-proto/-/ge",
  "t-proto-1.0.1.tgz\",\"version\":\"1.0.1\"},\"node_modules/gopd\":{\"engines\":{\"node\":\">= 0.4\"},\"funding\"",
  ":{\"url\":\"https://github.com/sponsors/ljharb\"},\"integrity\":\"sha512-ZUKRh6/kUFoAiTAtTYPZJ3hw9wNxx+",
  "BIBOijnlG9PnrJsCcSjs1wyyD6vJpaYtgnzDrKYRSqf3OO6Rfa93xsRg==\",\"license\":\"MIT\",\"resolved\":\"https://",
  "registry.npmjs.org/gopd/-/gopd-1.2.0.tgz\",\"version\":\"1.2.0\"},\"node_modules/has-symbols\":{\"engine",
  "s\":{\"node\":\">= 0.4\"},\"funding\":{\"url\":\"https://github.com/sponsors/ljharb\"},\"integrity\":\"sha512-",
  "1cDNdwJ2Jaohmb3sg4OmKaMBwuC48sYni5HUw2DvsC8LjGTLK9h+eb1X6RyuOHe4hT0ULCW68iomhjUoKUqlPQ==\",\"licen",
  "se\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/has-symbols/-/has-symbols-1.1.0.tgz\",\"version\":",
  "\"1.1.0\"},\"node_modules/hasown\":{\"dependencies\":{\"function-bind\":\"^1.1.2\"},\"engines\":{\"node\":\">= ",
  "0.4\"},\"integrity\":\"sha512-T2UbfbBEF32wiepXIsMlTW9+dDYC6wMh/t/vYA4tuOMKqWz/n3vr1NFSxQiyP+zk2mXsoM",
  "A/i/7qV6LKut1t1A==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/hasown/-/hasown-2.0.4",
  ".tgz\",\"version\":\"2.0.4\"},\"node_modules/http-errors\":{\"dependencies\":{\"depd\":\"~2.0.0\",\"inherits\":",
  "\"~2.0.4\",\"setprototypeof\":\"~1.2.0\",\"statuses\":\"~2.0.2\",\"toidentifier\":\"~1.0.1\"},\"engines\":{\"node",
  "\":\">= 0.8\"},\"funding\":{\"type\":\"opencollective\",\"url\":\"https://opencollective.com/express\"},\"inte",
  "grity\":\"sha512-4FbRdAX+bSdmo4AUFuS0WNiPz8NgFt+r8ThgNWmlrjQjt1Q7ZR9+zTlce2859x4KSXrwIsaeTqDoKQmtP",
  "8pLmQ==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/http-errors/-/http-errors-2.0.1.",
  "tgz\",\"version\":\"2.0.1\"},\"node_modules/iconv-lite\":{\"dependencies\":{\"safer-buffer\":\">= 2.1.2 < 3.",
  "0.0\"},\"engines\":{\"node\":\">=0.10.0\"},\"funding\":{\"type\":\"opencollective\",\"url\":\"https://opencollec",
  "tive.com/express\"},\"integrity\":\"sha512-IKXpvIzjnC9XTAUbVBcMfGS0EPaIXtW6v+zr+RRp+hqULEpo0owZax6wy",
  "RwPOJbWbzjYspQwusTsfVr0ifh4uQ==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/iconv-li",
  "te/-/iconv-lite-0.7.3.tgz\",\"version\":\"0.7.3\"},\"node_modules/inherits\":{\"integrity\":\"sha512-k/vGa",
  "X4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==\",\"license\":\"",
  "ISC\",\"resolved\":\"https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz\",\"version\":\"2.0.4\"},\"n",
  "ode_modules/ipaddr.js\":{\"engines\":{\"node\":\">= 0.10\"},\"integrity\":\"sha512-0KI/607xoxSToH7GjN1FfSb",
  "LoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==\",\"license\":\"MIT\",\"resolved\":\"h",
  "ttps://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz\",\"version\":\"1.9.1\"},\"node_modules/is-p",
  "romise\":{\"integrity\":\"sha512-hvpoI6korhJMnej285dSg6nu1+e6uxs7zG3BYAm5byqDsgJNWwxzM6z6iZiAgQR4TJ3",
  "0JmBTOwqZUw3WlyH3AQ==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/is-promise/-/is-pr",
  "omise-4.0.0.tgz\",\"version\":\"4.0.0\"},\"node_modules/math-intrinsics\":{\"engines\":{\"node\":\">= 0.4\"},",
  "\"integrity\":\"sha512-/IXtbwEk5HTPyEwyKX6hGkYXxM9nbj64B+ilVJnC/R6B0pH5G4V3b0pVbL7DBj4tkhBAppbQUlf6",
  "F6Xl9LHu1g==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/math-intrinsics/-/math-intr",
  "insics-1.1.0.tgz\",\"version\":\"1.1.0\"},\"node_modules/media-typer\":{\"engines\":{\"node\":\">= 0.8\"},\"in",
  "tegrity\":\"sha512-aisnrDP4GNe06UcKFnV5bfMNPBUw4jsLGaWwWfnH3v02GnBuXX2MCVn5RbrWo0j3pczUilYblq7fQ7N",
  "w2t5XKw==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/media-typer/-/media-typer-1.1.",
  "0.tgz\",\"version\":\"1.1.0\"},\"node_modules/merge-descriptors\":{\"engines\":{\"node\":\">=18\"},\"funding\":",
  "{\"url\":\"https://github.com/sponsors/sindresorhus\"},\"integrity\":\"sha512-Snk314V5ayFLhp3fkUREub6Wt",
  "jBfPdCPY1Ln8/8munuLuiYhsABgBVWsozAG+MWMbVEvcdcpbi9R7ww22l9Q3g==\",\"license\":\"MIT\",\"resolved\":\"htt",
  "ps://registry.npmjs.org/merge-descriptors/-/merge-descriptors-2.0.0.tgz\",\"version\":\"2.0.0\"},\"nod",
  "e_modules/mime-db\":{\"engines\":{\"node\":\">= 0.6\"},\"integrity\":\"sha512-aU5EJuIN2WDemCcAp2vFBfp/m4EA",
  "hWJnUNSSw0ixs7/kXbd6Pg64EmwJkNdFhB8aWt1sH2CTXrLxo/iAGV3oPQ==\",\"license\":\"MIT\",\"resolved\":\"https:",
  "//registry.npmjs.org/mime-db/-/mime-db-1.54.0.tgz\",\"version\":\"1.54.0\"},\"node_modules/mime-types\"",
  ":{\"dependencies\":{\"mime-db\":\"^1.54.0\"},\"engines\":{\"node\":\">=18\"},\"funding\":{\"type\":\"opencollecti",
  "ve\",\"url\":\"https://opencollective.com/express\"},\"integrity\":\"sha512-Lbgzdk0h4juoQ9fCKXW4by0UJqj+",
  "nOOrI9MJ1sSj4nI8aI2eo1qmvQEie4VD1glsS250n15LsWsYtCugiStS5A==\",\"license\":\"MIT\",\"resolved\":\"https:",
  "//registry.npmjs.org/mime-types/-/mime-types-3.0.2.tgz\",\"version\":\"3.0.2\"},\"node_modules/ms\":{\"i",
  "ntegrity\":\"sha512-6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tX",
  "tF3WRTlA==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/ms/-/ms-2.1.3.tgz\",\"version\":",
  "\"2.1.3\"},\"node_modules/negotiator\":{\"engines\":{\"node\":\">= 0.6\"},\"integrity\":\"sha512-8Ofs/AUQh8Ma",
  "Ecrlq5xOX0CQ9ypTF5dl78mjlMNfOK08fzpgTHQRQPBxcPlEtIw0yRpws+Zo/3r+5WRby7u3Gg==\",\"license\":\"MIT\",\"r",
  "esolved\":\"https://registry.npmjs.org/negotiator/-/negotiator-1.0.0.tgz\",\"version\":\"1.0.0\"},\"node",
  "_modules/object-inspect\":{\"engines\":{\"node\":\">= 0.4\"},\"funding\":{\"url\":\"https://github.com/spons",
  "ors/ljharb\"},\"integrity\":\"sha512-W67iLl4J2EXEGTbfeHCffrjDfitvLANg0UlX3wFUUSTx92KXRFegMHUVgSqE+wv",
  "hAbi4WqjGg9czysTV2Epbew==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/object-inspect",
  "/-/object-inspect-1.13.4.tgz\",\"version\":\"1.13.4\"},\"node_modules/on-finished\":{\"dependencies\":{\"e",
  "e-first\":\"1.1.1\"},\"engines\":{\"node\":\">= 0.8\"},\"integrity\":\"sha512-oVlzkg3ENAhCk2zdv7IJwd/QUD4z2R",
  "xRwpkcGY8psCVcCYZNq4wYnVWALHM+brtuJjePWiYF/ClmuDr8Ch5+kg==\",\"license\":\"MIT\",\"resolved\":\"https://",
  "registry.npmjs.org/on-finished/-/on-finished-2.4.1.tgz\",\"version\":\"2.4.1\"},\"node_modules/once\":{",
  "\"dependencies\":{\"wrappy\":\"1\"},\"integrity\":\"sha512-lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaE",
  "qe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==\",\"license\":\"ISC\",\"resolved\":\"https://registry.npmjs.o",
  "rg/once/-/once-1.4.0.tgz\",\"version\":\"1.4.0\"},\"node_modules/parseurl\":{\"engines\":{\"node\":\">= 0.8\"",
  "},\"integrity\":\"sha512-CiyeOxFT/JZyN5m0z9PfXw4SCBJ6Sygz1Dpl0wqjlhDEGGBP1GnsUVEL0p63hoG1fcj3fHynXi",
  "9NYO4nWOL+qQ==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/parseurl/-/parseurl-1.3.3",
  ".tgz\",\"version\":\"1.3.3\"},\"node_modules/path-to-regexp\":{\"funding\":{\"type\":\"opencollective\",\"url\"",
  ":\"https://opencollective.com/express\"},\"integrity\":\"sha512-qRcuIdP69NPm4qbACK+aDogI5CBDMi1jKe0ry",
  "5rSQJz8JVLsC7jV8XpiJjGRLLol3N+R5ihGYcrPLTno6pAdBA==\",\"license\":\"MIT\",\"resolved\":\"https://registr",
  "y.npmjs.org/path-to-regexp/-/path-to-regexp-8.4.2.tgz\",\"version\":\"8.4.2\"},\"node_modules/proxy-ad",
  "dr\":{\"dependencies\":{\"forwarded\":\"0.2.0\",\"ipaddr.js\":\"1.9.1\"},\"engines\":{\"node\":\">= 0.10\"},\"inte",
  "grity\":\"sha512-llQsMLSUDUPT44jdrU/O37qlnifitDP+ZwrmmZcoSKyLKvtZxpyV0n2/bD/N4tBAAZ/gJEdZU7KMraoK1",
  "+XYAg==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.7.tg",
  "z\",\"version\":\"2.0.7\"},\"node_modules/qs\":{\"dependencies\":{\"es-define-property\":\"^1.0.1\",\"side-cha",
  "nnel\":\"^1.1.1\"},\"engines\":{\"node\":\">=0.6\"},\"funding\":{\"url\":\"https://github.com/sponsors/ljharb\"",
  "},\"integrity\":\"sha512-O9gl3zCl5h5blw1KGUzQKhA5oUXSl8rwUIM5o0S3nCXMliSvy5Dzx7/DJcI+SwgICv+IneSZwh",
  "Bh1oSyEHA71A==\",\"license\":\"BSD-3-Clause\",\"resolved\":\"https://registry.npmjs.org/qs/-/qs-6.15.3.t",
  "gz\",\"version\":\"6.15.3\"},\"node_modules/range-parser\":{\"engines\":{\"node\":\">= 0.6\"},\"funding\":{\"typ",
  "e\":\"opencollective\",\"url\":\"https://opencollective.com/express\"},\"integrity\":\"sha512-hek2mFQpPuI4",
  "E1BBKrSto+BU3e3x4xuarsbiwr3+lf7p44juvFMV0XFWQAP3xUyqXA4RrXLIoaSUGbSt056ZMw==\",\"license\":\"MIT\",\"r",
  "esolved\":\"https://registry.npmjs.org/range-parser/-/range-parser-1.3.0.tgz\",\"version\":\"1.3.0\"},\"",
  "node_modules/raw-body\":{\"dependencies\":{\"bytes\":\"~3.1.2\",\"http-errors\":\"~2.0.1\",\"iconv-lite\":\"~0",
  ".7.0\",\"unpipe\":\"~1.0.0\"},\"engines\":{\"node\":\">= 0.10\"},\"integrity\":\"sha512-K5zQjDllxWkf7Z5xJdV0/B",
  "0WTNqx6vxG70zJE4N0kBs4LovmEYWJzQGxC9bS9RAKu3bgM40lrd5zoLJ12MQ5BA==\",\"license\":\"MIT\",\"resolved\":\"",
  "https://registry.npmjs.org/raw-body/-/raw-body-3.0.2.tgz\",\"version\":\"3.0.2\"},\"node_modules/route",
  "r\":{\"dependencies\":{\"debug\":\"^4.4.0\",\"depd\":\"^2.0.0\",\"is-promise\":\"^4.0.0\",\"parseurl\":\"^1.3.3\",\"",
  "path-to-regexp\":\"^8.0.0\"},\"engines\":{\"node\":\">= 18\"},\"integrity\":\"sha512-nLTrUKm2UyiL7rlhapu/Zl4",
  "5FwNgkZGaCpZbIHajDYgwlJCOzLSk+cIPAnsEqV955GjILJnKbdQC1nVPz+gAYQ==\",\"license\":\"MIT\",\"resolved\":\"h",
  "ttps://registry.npmjs.org/router/-/router-2.2.0.tgz\",\"version\":\"2.2.0\"},\"node_modules/safer-buff",
  "er\":{\"integrity\":\"sha512-YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcy",
  "RHk0cbwqcQriUtg==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/safer-buffer/-/safer-b",
  "uffer-2.1.2.tgz\",\"version\":\"2.1.2\"},\"node_modules/send\":{\"dependencies\":{\"debug\":\"^4.4.3\",\"encod",
  "eurl\":\"^2.0.0\",\"escape-html\":\"^1.0.3\",\"etag\":\"^1.8.1\",\"fresh\":\"^2.0.0\",\"http-errors\":\"^2.0.1\",\"m",
  "ime-types\":\"^3.0.2\",\"ms\":\"^2.1.3\",\"on-finished\":\"^2.4.1\",\"range-parser\":\"^1.2.1\",\"statuses\":\"^2.",
  "0.2\"},\"engines\":{\"node\":\">= 18\"},\"funding\":{\"type\":\"opencollective\",\"url\":\"https://opencollectiv",
  "e.com/express\"},\"integrity\":\"sha512-1gnZf7DFcoIcajTjTwjwuDjzuz4PPcY2StKPlsGAQ1+YH20IRVrBaXSWmdjo",
  "wTJ6u8Rc01PoYOGHXfP1mYcZNQ==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/send/-/send",
  "-1.2.1.tgz\",\"version\":\"1.2.1\"},\"node_modules/serve-static\":{\"dependencies\":{\"encodeurl\":\"^2.0.0\"",
  ",\"escape-html\":\"^1.0.3\",\"parseurl\":\"^1.3.3\",\"send\":\"^1.2.0\"},\"engines\":{\"node\":\">= 18\"},\"funding",
  "\":{\"type\":\"opencollective\",\"url\":\"https://opencollective.com/express\"},\"integrity\":\"sha512-xRXBn",
  "0pPqQTVQiC8wyQrKs2MOlX24zQ0POGaj0kultvoOCstBQM5yvOhAVSUwOMjQtTvsPWoNCHfPGwaaQJhTw==\",\"license\":\"",
  "MIT\",\"resolved\":\"https://registry.npmjs.org/serve-static/-/serve-static-2.2.1.tgz\",\"version\":\"2.",
  "2.1\"},\"node_modules/setprototypeof\":{\"integrity\":\"sha512-E5LDX7Wrp85Kil5bhZv46j8jOeboKq5JMmYM3gV",
  "GdGH8xFpPWXUMsNrlODCrkoxMEeNi/XZIwuRvY4XNwYMJpw==\",\"license\":\"ISC\",\"resolved\":\"https://registry.",
  "npmjs.org/setprototypeof/-/setprototypeof-1.2.0.tgz\",\"version\":\"1.2.0\"},\"node_modules/side-chann",
  "el\":{\"dependencies\":{\"es-errors\":\"^1.3.0\",\"object-inspect\":\"^1.13.4\",\"side-channel-list\":\"^1.0.1",
  "\",\"side-channel-map\":\"^1.0.1\",\"side-channel-weakmap\":\"^1.0.2\"},\"engines\":{\"node\":\">= 0.4\"},\"fund",
  "ing\":{\"url\":\"https://github.com/sponsors/ljharb\"},\"integrity\":\"sha512-6x6dK6zJdpTzF4sQeNYxwtvBzf",
  "6Eg4GtlesS94HOvTudUeyK2WXAaIfmDgsyslYrRBeFIlsi54AYsFGUuhmvrQ==\",\"license\":\"MIT\",\"resolved\":\"http",
  "s://registry.npmjs.org/side-channel/-/side-channel-1.1.1.tgz\",\"version\":\"1.1.1\"},\"node_modules/s",
  "ide-channel-list\":{\"dependencies\":{\"es-errors\":\"^1.3.0\",\"object-inspect\":\"^1.13.4\"},\"engines\":{\"",
  "node\":\">= 0.4\"},\"funding\":{\"url\":\"https://github.com/sponsors/ljharb\"},\"integrity\":\"sha512-mjn/0",
  "bi/oUURjc5Xl7IaWi/OJJJumuoJFQJfDDyO46+hBWsfaVM65TBHq2eoZBhzl9EchxOijpkbRC8SVBQU0w==\",\"license\":\"",
  "MIT\",\"resolved\":\"https://registry.npmjs.org/side-channel-list/-/side-channel-list-1.0.1.tgz\",\"ve",
  "rsion\":\"1.0.1\"},\"node_modules/side-channel-map\":{\"dependencies\":{\"call-bound\":\"^1.0.2\",\"es-error",
  "s\":\"^1.3.0\",\"get-intrinsic\":\"^1.2.5\",\"object-inspect\":\"^1.13.3\"},\"engines\":{\"node\":\">= 0.4\"},\"fu",
  "nding\":{\"url\":\"https://github.com/sponsors/ljharb\"},\"integrity\":\"sha512-VCjCNfgMsby3tTdo02nbjtM/",
  "ewra6jPHmpThenkTYh8pG9ucZ/1P8So4u4FGBek/BjpOVsDCMoLA/iuBKIFXRA==\",\"license\":\"MIT\",\"resolved\":\"ht",
  "tps://registry.npmjs.org/side-channel-map/-/side-channel-map-1.0.1.tgz\",\"version\":\"1.0.1\"},\"node",
  "_modules/side-channel-weakmap\":{\"dependencies\":{\"call-bound\":\"^1.0.2\",\"es-errors\":\"^1.3.0\",\"get-",
  "intrinsic\":\"^1.2.5\",\"object-inspect\":\"^1.13.3\",\"side-channel-map\":\"^1.0.1\"},\"engines\":{\"node\":\">",
  "= 0.4\"},\"funding\":{\"url\":\"https://github.com/sponsors/ljharb\"},\"integrity\":\"sha512-WPS/HvHQTYnHi",
  "sLo9McqBHOJk2FkHO/tlpvldyrnem4aeQp4hai3gythswg6p01oSoTl58rcpiFAjF2br2Ak2A==\",\"license\":\"MIT\",\"re",
  "solved\":\"https://registry.npmjs.org/side-channel-weakmap/-/side-channel-weakmap-1.0.2.tgz\",\"vers",
  "ion\":\"1.0.2\"},\"node_modules/statuses\":{\"engines\":{\"node\":\">= 0.8\"},\"integrity\":\"sha512-DvEy55V3D",
  "B7uknRo+4iOGT5fP1slR8wQohVdknigZPMpMstaKJQWhwiYBACJE3Ul2pTnATihhBYnRhZQHGBiRw==\",\"license\":\"MIT\"",
  ",\"resolved\":\"https://registry.npmjs.org/statuses/-/statuses-2.0.2.tgz\",\"version\":\"2.0.2\"},\"node_",
  "modules/toidentifier\":{\"engines\":{\"node\":\">=0.6\"},\"integrity\":\"sha512-o5sSPKEkg/DIQNmH43V0/uerLr",
  "pzVedkUh8tGNvaeXpfpuwjKenlSox/2O/BTlZUtEe+JG7s5YhEz608PlAHRA==\",\"license\":\"MIT\",\"resolved\":\"http",
  "s://registry.npmjs.org/toidentifier/-/toidentifier-1.0.1.tgz\",\"version\":\"1.0.1\"},\"node_modules/t",
  "ype-is\":{\"dependencies\":{\"content-type\":\"^2.0.0\",\"media-typer\":\"^1.1.0\",\"mime-types\":\"^3.0.0\"},\"",
  "engines\":{\"node\":\">= 18\"},\"funding\":{\"type\":\"opencollective\",\"url\":\"https://opencollective.com/e",
  "xpress\"},\"integrity\":\"sha512-faYHw0anBbc/kWF3zFTEnxSFOAGUX9GFbOBthvDdLsIlEoWOFOtS0zgCiQYwIskL9iG",
  "XZL3kAXD8OoZ4GmMATA==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/type-is/-/type-is-",
  "2.1.0.tgz\",\"version\":\"2.1.0\"},\"node_modules/type-is/node_modules/content-type\":{\"engines\":{\"node",
  "\":\">=18\"},\"funding\":{\"type\":\"opencollective\",\"url\":\"https://opencollective.com/express\"},\"integr",
  "ity\":\"sha512-j/O/d7GcZCyNl7/hwZAb606rzqkyvaDctLmckbxLzHvFBzTJHuGEdodATcP3yIRoDrLHkIATJuvzbFlp/ki",
  "2cQ==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/content-type/-/content-type-2.0.0.",
  "tgz\",\"version\":\"2.0.0\"},\"node_modules/typescript\":{\"bin\":{\"tsc\":\"bin/tsc\",\"tsserver\":\"bin/tsserv",
  "er\"},\"dev\":true,\"engines\":{\"node\":\">=14.17\"},\"integrity\":\"sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9Qj",
  "vBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==\",\"license\":\"Apache-2.0\",\"resolved\":\"ht",
  "tps://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz\",\"version\":\"5.9.3\"},\"node_modules/und",
  "ici-types\":{\"dev\":true,\"integrity\":\"sha512-iwDZqg0QAGrg9Rav5H4n0M64c3mkR59cJ6wQp+7C4nI0gsmExaeda",
  "YLNO44eT4AtBBwjbTiGPMlt2Md0T9H9JQ==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/undi",
  "ci-types/-/undici-types-6.21.0.tgz\",\"version\":\"6.21.0\"},\"node_modules/unpipe\":{\"engines\":{\"node\"",
  ":\">= 0.8\"},\"integrity\":\"sha512-pjy2bYhSsufwWlKwPc+l3cN7+wuJlK6uz0YdJEOlQDbl6jo/YlPi4mb8agUkVC8BF",
  "7V8NuzeyPNqRksA3hztKQ==\",\"license\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/unpipe/-/unpipe-",
  "1.0.0.tgz\",\"version\":\"1.0.0\"},\"node_modules/vary\":{\"engines\":{\"node\":\">= 0.8\"},\"integrity\":\"sha5",
  "12-BNGbWLfd0eUPabhkXUVm0j8uuvREyTh5ovRa/dyow/BqAbZJyC+5fU+IzQOzmAKzYqYRAISoRhdQr3eIZ/PXqg==\",\"li",
  "cense\":\"MIT\",\"resolved\":\"https://registry.npmjs.org/vary/-/vary-1.1.2.tgz\",\"version\":\"1.1.2\"},\"n",
  "ode_modules/wrappy\":{\"integrity\":\"sha512-l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3",
  "u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==\",\"license\":\"ISC\",\"resolved\":\"https://registry.npmjs.org/wrappy",
  "/-/wrappy-1.0.2.tgz\",\"version\":\"1.0.2\"}},\"requires\":true,\"version\":\"0.0.0\"}\n",
);
export const NODE_EXPRESS_API_TSCONFIG_JSON_TEXT_V2 = textV2(
  "{\"compilerOptions\":{\"esModuleInterop\":true,\"forceConsistentCasingInFileNames\":true,\"module\":\"Nod",
  "eNext\",\"moduleResolution\":\"NodeNext\",\"noEmitOnError\":true,\"outDir\":\"dist\",\"resolveJsonModule\":tr",
  "ue,\"rootDir\":\"src\",\"strict\":true,\"target\":\"ES2022\",\"verbatimModuleSyntax\":true},\"exclude\":[\"dist",
  "\",\"node_modules\"],\"include\":[\"src/**/*.ts\"]}\n",
);

export const NODE_SCAFFOLD_CANONICAL_TEXT_BY_PROFILE_V2 = Object.freeze({
  PROFILE_NODE_CLI_STATELESS_EXACT_V2: Object.freeze({
    packageJson: NODE_CLI_PACKAGE_JSON_TEXT_V2,
    packageLockJson: NODE_CLI_PACKAGE_LOCK_JSON_TEXT_V2,
    tsconfigJson: NODE_CLI_TSCONFIG_JSON_TEXT_V2,
  }),
  PROFILE_NODE_EXPRESS_API_STATELESS_EXACT_V2: Object.freeze({
    packageJson: NODE_EXPRESS_API_PACKAGE_JSON_TEXT_V2,
    packageLockJson: NODE_EXPRESS_API_PACKAGE_LOCK_JSON_TEXT_V2,
    tsconfigJson: NODE_EXPRESS_API_TSCONFIG_JSON_TEXT_V2,
  }),
} as const);
