// Generated by scripts/check-contract-spine-migration-digests.ts --write.
// Do not hand-edit. Source-mode migration commands and prebuild verify these
// values against exact semantic regions and declared helper dependency files.
export const CONTRACT_SPINE_SEMANTIC_MIGRATION_DIGESTS = Object.freeze({
  8: "e5262ada2f854b5897d19b203e7db360f54f9f17686e4d33bbf86b4316f4dcd4",
  11: "1de0344e33f33f0241b694b3c96a36b31c9282fa7cd35697ad300dc3279ebf3f",
  12: "7a82f7e50421410dc5aded4fd2b61ce9d6c7b9be7db9f46920edbed7ad330b84",
  23: "dfeac8a3e38de094192e21d0281ff28330ae75d1227c994920f9a35c1b48e7fe",
  24: "62fd9d92eaceffee527aa734b1ae91b17594e4898750b0468bbe9d6acd9b75b4",
  25: "bd2aaf747f7937bddd8ccad9d6dfce9dad2eb467f3910aa01e8346cc82ce301f",
  26: "ad37c7710fae8f8eb9f1ff518368e67e20599ac7c316781261eef328738a67d9",
  27: "6c88521537665a21e0167373b12f35215aac3cd74eb06978b162a04ab7f4fb89",
  28: "cb6b68777f143c1b55ad38e66d42254745241b82e95a8e06e4898bb047ddfdcd",
  29: "b0a2cb9163bc87a6e9e45f8ba230c55821c85d14458697b72b2a6e17d7dcb305",
  30: "95c2f97df36fc274a03dd546a262436d003c822b2698ef4410d0da1933193c4c",
  31: "f052eff1b45df0f00ffb844fe0d23b542eafa4789da5e90a329a8d756dfcdc3a",
  32: "8cbaab0c47bf3639033442d2df9a1c15d421eb34adbab72fa82951712cafe4e2",
  33: "d3d0308a6c855a4badc4ad091c5b5807842310e8ec86d8e6e2cd2f395f58967c",
} as const);

export type ContractSpineSemanticMigrationVersion =
  keyof typeof CONTRACT_SPINE_SEMANTIC_MIGRATION_DIGESTS;
